### ISSUE TITLE
Investigate repeating event error

### ISSUE THREAD

**Issue by Ingvord** [waltz-controls/waltz#236]
```
error: TangoProxyException:unknown:java.util.concurrent.RejectedExecutionException[Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@d8bd1fa rejected from java.util.concurrent.ScheduledThreadPoolExecutor@57c8d763[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 8648]]"
```

**Comment by Ingvord** [comment]
Exception in JTango:

```
ERROR 2019-12-15 12:45:21,609 [RequestProcessor-4 - dserver/StatusServer2/test] org.tango.server.servant.DeviceImpl.logDevFailed:128 - Error Level 0 :
ERROR 2019-12-15 12:45:21,609 [RequestProcessor-4 - dserver/StatusServer2/test] org.tango.server.servant.DeviceImpl.logDevFailed:129 -   - desc: Task java.util.concurrent.ScheduledThreadPoo
lExecutor$ScheduledFutureTask@57c967f0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@567ef3e8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tas
ks = 8523]
ERROR 2019-12-15 12:45:21,609 [RequestProcessor-4 - dserver/StatusServer2/test] org.tango.server.servant.DeviceImpl.logDevFailed:130 -   - origin: java.util.concurrent.RejectedExecutionExce
ption: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@57c967f0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@567ef3e8[Terminated, pool size = 0,
active threads = 0, queued tasks = 0, completed tasks = 8523]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
        at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
        at org.tango.server.events.EventManager.initialize(EventManager.java:173)
        at org.tango.server.events.EventManager.subscribe(EventManager.java:379)
        at org.tango.server.admin.AdminDevice.subscribeEvent(AdminDevice.java:815)
        at org.tango.server.admin.AdminDevice.zmqEventSubscriptionChange(AdminDevice.java:657)
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.tango.server.command.ReflectCommandBehavior.execute(ReflectCommandBehavior.java:63)
        at org.tango.server.command.CommandImpl.execute(CommandImpl.java:87)
        at org.tango.server.servant.DeviceImpl.commandHandler(DeviceImpl.java:1577)

```

**Comment by Ingvord** [comment]
Upstream issue
